services:
  - type: web
    name: castles-reforged
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=300
